name: Build App for Linux

# Only trigger this workflow when a new tag is pushed
on:
  push:
    tags:
     - "*"
  pull_request:
    branches: [ master ]
  release:
    types: [published, prereleased]


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Configure python 3.9
      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Tkinter for Ubuntu
        run: sudo apt-get install python3-tk

      - name: Install virtual envs and dependencies
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install pipenv dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Build Linux executable
        run: |
          pipenv run pyinstaller --hidden-import=tkinter --name="app_linux" --onefile app.py
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/app_linux

